export default {
  // id:
  // arrivalDecimal
  // departureDecimal
  "Vehicle working number": 'vehicleWorkingNumber',
  "Vehicle working designation": 'vehicleWorkingDesignation',
  "Date": 'date',
  "Date (planned arrival)": 'arrivalDate',
  "Planned arrival": 'arrivalPlanned',
  "Actual arrival": 'arrivalActual',
  "Arrival time last revenue trip": 'arrivalTimeLastRevenueTrip',
  "Depot arrival": 'arrivalDepot',
  "Trip number (arrival)": 'arrivalTripNumber',
  "Train reference (arrival)": 'arrivalTrainNumber',
  "Network train number (arrival)": 'arrivalNetworkTrainNumber',
  "Route (arrival)": 'arrivalRoute',
  "Starting location": 'startingLocation',
  "Date (planned departure)": 'departureDate',
  "Planned departure": 'departurePlanned',
  "Actual departure": 'departureActual',
  "Departure time first revenue trip": 'departureTimeFirstRevenueTrip',
  "Depot departure": 'departureDepot',
  "Trip number (departure)": 'departureTripNumber',
  "Train reference (departure)": 'departureTrainNumber',
  "Network train number (departure)": 'departureNetworkTrainNumber',
  "End location": 'endLocation',
  "Home depot": 'homeDepot',
  "Route": 'route',
  "Route (departure)": 'departureRoute',
  "Route info": 'routeInfo',
  "Route (long name)": 'routeLongName',
  "Planned vehicle type": 'plannedVehicleType',
  "Vehicle": 'vehicleName',
  "Name of the vehicle group": 'vehicle',
  "Vehicle working km": 'vehicleWorkingKm',
  "Vehicle working series km": 'vehicleWorkingSeriesKm',
  "Start track": 'startingTrack',
  "Destination track": 'targetTrack',
  "Start track section": 'startTrackSection',
  "Destination track section": 'destinationTrackSection',
  "External vehicle number": 'externalVehicleNumber',
  "Registration number": 'registrationNumber',
  "Duty (departure)": 'departureDuty',
  "Duty (arrival)": 'arrivalDuty',
  "Description": 'description',
  "Duration": 'duration',
  "Vehicle working vehicle type": 'vehicleWorkingVehicleType',
  "Vehicle working vehicle type (description)": 'vehicleWorkingVehicleTypeDescription',
  "Actual vehicle type": 'actualVehicleType',
  "Employees (all)": 'employeesAll',
  "Duty (all)": 'dutyAll',
  "Employee 1 departure": 'departureEmployee1',
  "Employee 2 departure": 'departureEmployee2',
  "Employee 3 departure": 'departureEmployee3',
  "Employee 1 arrival": 'arrivalEmployee1',
  "Employee 2 arrival": 'arrivalEmployee2',
  "Employee 3 arrival": 'arrivalEmployee3',
  "Synchronisation status": 'synchronisationStatus'
};
