export default {
  // id:
  // arrivalDecimal
  // departureDecimal
  date: 'Data',
  vehicleWorkingNumber: 'Riedmens parišimo numeris',
  vehicleWorkingDesignation: 'Riedmens parišimo žymėjimas',
  arrivalDate: 'Planuojamo atvykimo data',
  departureDate: 'Planuojamo išvykimo data',
  departurePlanned: 'Planuojamas išvykimas',
  departureActual: 'Faktinis išvykimas',
  arrivalPlanned: 'Planuojamas atvykimas',
  arrivalActual: 'Faktinis atvykimas',
  departureTimeFirstRevenueTrip: 'Pirmojo pajamų reiso išvykimo laikas',
  arrivalTimeLastRevenueTrip: 'Paskutinio pajamų reiso atvykimo laikas',
  departureDepot: 'Išvykimo depas',
  arrivalDepot: 'Atvykimo depas',
  startingLocation: 'Pradinė vieta',
  endLocation: 'Galutinė vieta',
  homeDepot: 'Namų depas',
  departureTripNumber: 'Išvykimo reiso numeris',
  arrivalTripNumber: 'Atvykimo reiso numeris',
  departureTrainNumber: 'Išvykimo traukinio numeris',
  arrivalTrainNumber: 'Atvykimo traukinio numeris',
  departureNetworkTrainNumber: 'Tinklo traukinio išvykimo numeris',
  arrivalNetworkTrainNumber: 'Tinklo traukinio atvykimo numeris',
  route: 'Maršrutas',
  departureRoute: 'Išvykimo maršrutas',
  arrivalRoute: 'Atvykimo maršrutas',
  routeInfo: 'Maršruto informacija',
  routeLongName: 'Maršrutas (ilgas pavadinimas)',
  plannedVehicleType: 'Planuojamas riedmens tipas',
  vehicleName: 'Riedmens pavadinimas',
  vehicle: 'Riedmuo',
  vehicleWorkingKm: 'Riedmens parišimo kilometrai',
  vehicleWorkingSeriesKm: 'Riedmens parišimo serijos kilometrai',
  startingTrack: 'Pradinis kelias',
  targetTrack: 'Tikslo kelias',
  startTrackSection: 'Pradinio kelio sekcija',
  destinationTrackSection: 'Paskirties kelio sekcija',
  externalVehicleNumber: 'Išorinis riedmens numeris',
  registrationNumber: 'Registracijos numeris',
  departureDuty: 'Išvykimo pamaina',
  arrivalDuty: 'Atvykimo pamaina',
  description: 'Aprašymas',
  duration: 'Trukmė',
  vehicleWorkingVehicleType: 'Riedmens parišimo riedmens tipas',
  vehicleWorkingVehicleTypeDescription: 'Riedmens parišimo riedmens tipo aprašymas',
  actualVehicleType: 'Faktinis riedmens tipas',
  employeesAll: 'Visi darbuotojai',
  dutyAll: 'Visos pamainos',
  departureEmployee1: 'Pirmo darbuotojo išvykimas',
  departureEmployee2: 'Antro darbuotojo išvykimas',
  departureEmployee3: 'Trečio darbuotojo išvykimas',
  arrivalEmployee1: 'Pirmo darbuotojo atvykimas',
  arrivalEmployee2: 'Antro darbuotojo atvykimas',
  arrivalEmployee3: 'Trečio darbuotojo atvykimas',
  synchronisationStatus: 'Sinchronizacijos būsena'
};
