export default {
  date: 'Дата',
  vehicleWorkingNumber: 'Номер подвязки состава',
  vehicleWorkingDesignation: 'Обозначение подвязки состава',
  arrivalDate: 'Дата планового прибытия',
  departureDate: 'Дата планового отправления',
  departurePlanned: 'Плановое отправление',
  departureActual: 'Фактическое отправление',
  arrivalPlanned: 'Плановое прибытие',
  arrivalActual: 'Фактическое прибытие',
  departureTimeFirstRevenueTrip: 'Время отправления первого доходного рейса',
  arrivalTimeLastRevenueTrip: 'Время прибытия последнего доходного рейса',
  departureDepot: 'Депо отправления',
  arrivalDepot: 'Депо прибытия',
  startingLocation: 'Начальное местоположение',
  endLocation: 'Конечное местоположение',
  homeDepot: 'Домашнее депо',
  departureTripNumber: 'Номер рейса отправления',
  arrivalTripNumber: 'Номер рейса прибытия',
  departureTrainNumber: 'Номер поезда отправления',
  arrivalTrainNumber: 'Номер поезда прибытия',
  departureNetworkTrainNumber: 'Сетевой номер поезда отправления',
  arrivalNetworkTrainNumber: 'Сетевой номер поезда прибытия',
  route: 'Маршрут',
  departureRoute: 'Маршрут отправления',
  arrivalRoute: 'Маршрут прибытия',
  routeInfo: 'Информация о маршруте',
  routeLongName: 'Маршрут (полное название)',
  plannedVehicleType: 'Плановый тип состава',
  vehicleName: 'Состав',
  vehicle: 'Имя состава',
  vehicleWorkingKm: 'Километры подвязки состава',
  vehicleWorkingSeriesKm: 'Километры серии подвязки состава',
  startingTrack: 'Начальный путь',
  targetTrack: 'Целевой путь',
  startTrackSection: 'Секция начального пути',
  destinationTrackSection: 'Секция конечного пути',
  externalVehicleNumber: 'Внешний номер состава',
  registrationNumber: 'Регистрационный номер',
  departureDuty: 'Смена отправления',
  arrivalDuty: 'Смена прибытия',
  description: 'Описание',
  duration: 'Продолжительность',
  vehicleWorkingVehicleType: 'Тип состава подвязки',
  vehicleWorkingVehicleTypeDescription: 'Описание типа состава подвязки',
  actualVehicleType: 'Фактический тип состава',
  employeesAll: 'Все сотрудники',
  dutyAll: 'Все смены',
  departureEmployee1: 'Отправление 1-го сотрудника',
  departureEmployee2: 'Отправление 2-го сотрудника',
  departureEmployee3: 'Отправление 3-го сотрудника',
  arrivalEmployee1: 'Прибытие 1-го сотрудника',
  arrivalEmployee2: 'Прибытие 2-го сотрудника',
  arrivalEmployee3: 'Прибытие 3-го сотрудника',
  synchronisationStatus: 'Статус синхронизации'
};
